---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  remote_user: cloudy
  # remote_user: user
  become: yes
  # become_method: sudo
  vars_files: 
    - define-deployment-variables.yml

  roles:
    - apply-common-config
    - mysql
    - nginx
    - php-fpm
    - wordpress
