---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  remote_user: cloudy
  # remote_user: user
  become: yes
  # become_method: sudo

  roles:
    #- common
    - mysql
    - nginx
    - php-fpm
    - wordpress
